### ISSUE TITLE
Clicking on "About this app" crashes the app

### ISSUE THREAD

**Issue by dieechtenilente** [dieechtenilente/alcoholtestapp#38]

**Comment by okitec** [comment]
The app simply doesn't feel like talking about itself. No self-confidence nowadays :P

**Comment by dieechtenilente** [comment]
And I didn't notice that :(

**Comment by leletec** [comment]
In the `onOptionsItemSelected(MenuItem item)`, try using `AlertDialog` instead of `Dialog`.
So like
`AlertDialog.Builder builder = new AlertDialog.Builder(this);`
`builder.setTitle(R.string.about);`
`builder.setView(R.layout.dialog_about);`
`AlertDialog dialog = builder.create();`
`final TextView title = (TextView) dialog.findViewById(android.R.id.title);`
`title.setTextAlignment(View.TEXT_ALIGNMENT_CENTER);`
`title.setPadding(0, 32, 0, 4);`
`dialog.show();`

**Comment by leletec** [comment]
Not testet tho.

**Comment by okitec** [comment]
`AlertDialog.Builder builder = new AlertDialog.Builder(this);`

How I hate Java. I'm forced to use it for homework again and all the bad feelings come up again.
Fscking lang doesn't have first-class functions that you can store in variables and pass as parameters.
And the Type system is really cumbersome.

/rant

**Comment by dieechtenilente** [comment]
That was exactly my plan. But currently "builder.setView(R.layout.dialog_about);" doesn't work

**Comment by leletec** [comment]
> That was exactly my plan. But currently "builder.setView(R.layout.dialog_about);" doesn't work

I also had problems with it in the past... Maybe you can generate the `View` dynamically or on some other way?

**Comment by dieechtenilente** [comment]
I think, there is no title and in this case, there's no need for one anyways.
Next commit will fix this

**Comment by leletec** [comment]
Does `Dialog` not allow a title?

Alternatively you could switch to AlertDialog and not use the dialog_about.xml
The logo could be shown with `builder.setIcon`.

**Comment by dieechtenilente** [comment]
`Dialog `has a title, yup. But it is not visible if you bump a `customView `over it.
`AlertDialog `would do the same probably, but now it's fixed :P

**Comment by leletec** [comment]
Aight 😄
